// Mock API service for learning content
export interface LearningContent {
  id: string;
  title: string;
  subtitle: string;
  videoUrl: string;
  videoTitle: string;
  content: string;
  questions: Question[];
  homework: Homework[];
}

export interface Question {
  id: string;
  type: "multiple-choice" | "true-false" | "open-ended";
  title: string;
  content: string;
  options?: string[];
  correctAnswer?: string;
}

export interface Homework {
  id: string;
  type: "practice" | "quiz" | "assignment";
  title: string;
  content: string;
  dueDate?: string;
}

// Mock data for different chapters
const chapterData: Record<string, LearningContent> = {
  "chapter-1": {
    id: "chapter-1",
    title: "Introduction to Technical Analysis",
    subtitle: "Chapter 1: Understanding Chart Patterns",
    videoUrl: "https://www.youtube.com/watch?v=CQc7LMVlnOc",
    videoTitle: "Technical Analysis Fundamentals",
    content: `Technical analysis is a method of evaluating securities by analyzing statistics generated by market activity, such as past prices and volume. Technical analysts do not attempt to measure a security's intrinsic value, but instead use charts and other tools to identify patterns that can suggest future activity.

Key concepts covered in this chapter:
• Chart types and their applications
• Support and resistance levels
• Trend analysis and identification
• Volume analysis and its importance
• Moving averages and their significance

Understanding these fundamentals will provide you with the foundation needed to analyze market movements and make informed trading decisions.`,
    questions: [
      {
        id: "q1",
        type: "multiple-choice",
        title: "What is the primary purpose of technical analysis?",
        content:
          "Which of the following best describes the main goal of technical analysis in trading?",
        options: [
          "To determine a security's intrinsic value",
          "To identify patterns and predict future price movements",
          "To analyze company financial statements",
          "To calculate dividend yields",
        ],
        correctAnswer:
          "To identify patterns and predict future price movements",
      },
      {
        id: "q2",
        type: "true-false",
        title:
          "Support and resistance levels are key concepts in technical analysis",
        content:
          "True or False: Support and resistance levels help traders identify potential entry and exit points in the market.",
        correctAnswer: "True",
      },
      {
        id: "q3",
        type: "open-ended",
        title: "Explain the difference between support and resistance",
        content:
          "In your own words, describe how support and resistance levels work in technical analysis and why they are important for traders.",
      },
    ],
    homework: [
      {
        id: "hw1",
        type: "practice",
        title: "Chart Pattern Recognition",
        content:
          "Practice identifying common chart patterns on historical data. Look for head and shoulders, triangles, and flag patterns in the provided charts.",
      },
      {
        id: "hw2",
        type: "quiz",
        title: "Technical Analysis Quiz",
        content:
          "Complete a 10-question quiz covering the fundamentals of technical analysis, including chart types, indicators, and pattern recognition.",
        dueDate: "2024-01-15",
      },
      {
        id: "hw3",
        type: "assignment",
        title: "Market Analysis Report",
        content:
          "Analyze a selected stock using technical analysis principles. Create a report identifying key support/resistance levels and potential trading opportunities.",
        dueDate: "2024-01-20",
      },
    ],
  },
  "chapter-2": {
    id: "chapter-2",
    title: "Advanced Chart Patterns",
    subtitle: "Chapter 2: Complex Pattern Recognition",
    videoUrl: "https://www.youtube.com/watch?v=7aSwErJqoWQ",
    videoTitle: "Advanced Chart Patterns for Trading",
    content: `Advanced chart patterns are sophisticated formations that can provide powerful trading signals. These patterns often indicate significant market movements and can help traders identify high-probability trading opportunities.

Key advanced patterns covered:
• Head and Shoulders (regular and inverted)
• Double tops and bottoms
• Triple tops and bottoms
• Cup and handle patterns
• Flag and pennant patterns
• Wedge patterns (rising and falling)

These patterns require careful analysis and confirmation through volume and other technical indicators.`,
    questions: [
      {
        id: "q1",
        type: "multiple-choice",
        title: "Which pattern is considered a reversal pattern?",
        content:
          "Which of the following chart patterns typically indicates a potential trend reversal?",
        options: [
          "Flag pattern",
          "Head and shoulders",
          "Pennant pattern",
          "Channel pattern",
        ],
        correctAnswer: "Head and shoulders",
      },
      {
        id: "q2",
        type: "true-false",
        title: "Volume confirmation is important for pattern reliability",
        content:
          "True or False: High volume during pattern completion increases the reliability of the trading signal.",
        correctAnswer: "True",
      },
    ],
    homework: [
      {
        id: "hw1",
        type: "practice",
        title: "Pattern Identification Exercise",
        content:
          "Identify 5 different chart patterns on historical price charts and explain why each pattern is significant.",
      },
      {
        id: "hw2",
        type: "assignment",
        title: "Pattern Trading Strategy",
        content:
          "Develop a trading strategy based on a specific chart pattern. Include entry/exit rules and risk management.",
        dueDate: "2024-01-25",
      },
    ],
  },
  "chapter-3": {
    id: "chapter-3",
    title: "Technical Indicators",
    subtitle: "Chapter 3: Using Indicators for Analysis",
    videoUrl: "https://www.youtube.com/watch?v=8QqHhxKekvM",
    videoTitle: "Technical Indicators Explained",
    content: `Technical indicators are mathematical calculations based on price, volume, or other market data that help traders make informed decisions. They can be used to confirm trends, identify potential reversals, and measure market momentum.

Popular indicators covered:
• Moving Averages (Simple, Exponential, Weighted)
• Relative Strength Index (RSI)
• MACD (Moving Average Convergence Divergence)
• Bollinger Bands
• Stochastic Oscillator
• Average True Range (ATR)

Understanding how to combine multiple indicators can significantly improve trading accuracy.`,
    questions: [
      {
        id: "q1",
        type: "multiple-choice",
        title: "What does RSI measure?",
        content:
          "The Relative Strength Index (RSI) is primarily used to measure what?",
        options: [
          "Price momentum",
          "Volume trends",
          "Market volatility",
          "Support levels",
        ],
        correctAnswer: "Price momentum",
      },
      {
        id: "q2",
        type: "open-ended",
        title: "Explain MACD crossover signals",
        content:
          "Describe how MACD crossover signals work and what they indicate for traders.",
      },
    ],
    homework: [
      {
        id: "hw1",
        type: "practice",
        title: "Indicator Analysis",
        content:
          "Apply RSI and MACD to a stock chart and identify potential buy/sell signals.",
      },
      {
        id: "hw2",
        type: "quiz",
        title: "Indicators Quiz",
        content:
          "Complete a quiz on technical indicators, their calculations, and interpretation.",
        dueDate: "2024-02-01",
      },
    ],
  },
  "chapter-4": {
    id: "chapter-4",
    title: "Risk Management",
    subtitle: "Chapter 4: Protecting Your Capital",
    videoUrl: "https://www.youtube.com/watch?v=3nAOVZ9HZeo",
    videoTitle: "Risk Management in Trading",
    content: `Risk management is the most critical aspect of successful trading. It involves protecting your capital and managing potential losses to ensure long-term profitability.

Key risk management principles:
• Position sizing and risk per trade
• Stop-loss placement strategies
• Risk-reward ratios
• Portfolio diversification
• Maximum drawdown limits
• Emotional control and discipline

Remember: It's not about winning every trade, but about managing risk so that winning trades outweigh losing ones.`,
    questions: [
      {
        id: "q1",
        type: "multiple-choice",
        title: "What percentage of capital should you risk per trade?",
        content:
          "What is the recommended maximum percentage of your trading capital to risk on a single trade?",
        options: ["1-2%", "5-10%", "15-20%", "25-30%"],
        correctAnswer: "1-2%",
      },
      {
        id: "q2",
        type: "true-false",
        title: "Risk-reward ratio should be at least 1:2",
        content:
          "True or False: A good risk-reward ratio means potential profit should be at least twice the potential loss.",
        correctAnswer: "True",
      },
    ],
    homework: [
      {
        id: "hw1",
        type: "practice",
        title: "Risk Calculation Exercise",
        content:
          "Calculate position sizes for different account sizes and risk percentages.",
      },
      {
        id: "hw2",
        type: "assignment",
        title: "Risk Management Plan",
        content:
          "Create a comprehensive risk management plan for your trading strategy.",
        dueDate: "2024-02-05",
      },
    ],
  },
};

// Simulate API calls with delays
export const api = {
  async getLearningContent(chapterId: string): Promise<LearningContent> {
    // Simulate API delay
    await new Promise((resolve) => setTimeout(resolve, 500));

    // Simulate potential API error
    if (Math.random() < 0.1) {
      throw new Error("Failed to fetch learning content");
    }

    const content = chapterData[chapterId];
    if (!content) {
      throw new Error("Chapter not found");
    }

    return content;
  },

  async getChapterList(): Promise<
    { id: string; title: string; subtitle: string }[]
  > {
    await new Promise((resolve) => setTimeout(resolve, 300));

    return [
      {
        id: "chapter-1",
        title: "Introduction to Technical Analysis",
        subtitle: "Chapter 1: Understanding Chart Patterns",
      },
      {
        id: "chapter-2",
        title: "Advanced Chart Patterns",
        subtitle: "Chapter 2: Complex Pattern Recognition",
      },
      {
        id: "chapter-3",
        title: "Technical Indicators",
        subtitle: "Chapter 3: Using Indicators for Analysis",
      },
      {
        id: "chapter-4",
        title: "Risk Management",
        subtitle: "Chapter 4: Protecting Your Capital",
      },
    ];
  },
};
